### ISSUE TITLE
Java class errors when trying to visualise 

### ISSUE THREAD

**Issue by geejaytee** [viq854/lichee#11]
I'm trying to run the visualisation on a set of variants and get the following java error:

````$ java -jar lichee.jar -build P004.txt -maxVAFAbsent 0.005 -minVAFPresent 0.005 -n 0 -color -dot
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 3 more
````

This doesn't happen when I don't want visualisation as the output is purely a text file. 

I have checked that all my java packages and libraries are updated (ubuntu 20.04).

**Comment by geejaytee** [comment]
It turns out I'd not configured the environment properly so the classes couldn't be loaded.
