### ISSUE TITLE
Issue java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException

### ISSUE THREAD

**Issue by jamesdalg** [viq854/lichee#14]
Using the example, I'm getting a bit of an odd java error that popped up just this morning. I previously had used the program successfully. Here's an example using test data:

```
bash-4.2$ ./lichee -build -i ../data/ccRCC/RMH008.txt -maxVAFAbsent 0.005 -minVAFPresent 0.005 -n 0 -minPrivateClusterSize 2 -showTree 1 -color -dot
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 3 more
bash-4.2$ ls -l ../data/ccRCC/RMH008.txt
-rw-r--r-- 1 dalgleishjl CCRBioinfo 6297 Dec 23 22:24 ../data/ccRCC/RMH008.txt

```

**Comment by jamesdalg** [comment]
I would also add that this occurs when just loading the jar file:

```
bash-4.2$ java -jar lichee.jar
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 3 more

```

**Comment by 9421g** [comment]
# I'm not familiar with java, but deepseek helped me solve this problem easily !!!

```bash
cd lichee/LICHe

mkdir -p build/temp
cd build/temp
find ../../lib -name "*.jar" -exec jar xf {} \;
cd ../..

javac -cp "lib/*" -d build/temp src/lineage/*.java src/util/*.java

echo "Main-Class: lineage.LineageEngine" > build/MANIFEST.MF

jar cfm release/lichee.jar build/MANIFEST.MF -C build/temp .

```

omg
